INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_INTERFACEJRO_7 InterfaceJRO_7)

FIND_PATH(
    INTERFACEJRO_7_INCLUDE_DIRS
    NAMES InterfaceJRO_7/api.h
    HINTS $ENV{INTERFACEJRO_7_DIR}/include
        ${PC_INTERFACEJRO_7_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    INTERFACEJRO_7_LIBRARIES
    NAMES gnuradio-InterfaceJRO_7
    HINTS $ENV{INTERFACEJRO_7_DIR}/lib
        ${PC_INTERFACEJRO_7_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(INTERFACEJRO_7 DEFAULT_MSG INTERFACEJRO_7_LIBRARIES INTERFACEJRO_7_INCLUDE_DIRS)
MARK_AS_ADVANCED(INTERFACEJRO_7_LIBRARIES INTERFACEJRO_7_INCLUDE_DIRS)

